# name of the Workflow 
name: First Workflow

# Controls when the workflow will run
on: workflow_dispatch #the value of this event makes sure that we can manually trigger this workflow

# block that defines the jobs of the workflow
jobs:
  first-job:
    # runner which should run the job
    runs-on: ubuntu-latest
    # block to define the steps of the job. They are a yml list
    steps:
      # every strep have a name and a command
      - name: Print greeting
        run: echo "Hello Actions!"
      - name: Print goodbye
        run: echo "Bye Actions!"
